## Обратная задача кинематика (сверка с part1)

#### Импорты

In [20]:
import math

import numpy as np
import sympy as sy

from lab4.function4lab import positionsAndRotate, backKinematicsLab4

#### Координаты звеньев (theta1, d2, theta3)

In [21]:
joint_coords = [math.pi, -10, math.pi / 2]

#### Параметры Денавита-Хартенберга манипулятора

In [22]:
theta1, theta3, d2 = sy.symbols('theta1'), sy.symbols('theta3'), sy.symbols('d2')

d = [10, d2, 0, 5]
r = [0, 0, 0, 0]
thetas = [theta1, -math.pi / 2, -math.pi / 2 - math.pi / 4 + theta3, -math.pi / 2]
alpha = [-math.pi / 2 - math.pi / 4, -math.pi / 2, -math.pi / 2, 0]

#### Вычислении позиций и матрицы поворота в прямой задаче

In [23]:
arg = {theta1: joint_coords[0], d2: joint_coords[1], theta3: joint_coords[2]}
pos, R = positionsAndRotate(d, r, thetas, alpha, arg)

#### Вычислении координат звеньев в обратной задаче по результатам прямой

In [24]:
back_theta1, back_theta3, back_d2 = backKinematicsLab4(pos[-1][0], pos[-1][1], pos[-1][2], R)

#### Вычислении позиций и матрицы поворота в прямой задаче по результатам обратной

In [25]:
back_arg = {theta1: back_theta1, d2: back_d2, theta3: back_theta3}
pos_ik, R_ik = positionsAndRotate(d, r, thetas, alpha, back_arg)

###### Позиции по изначальным координатам звеньев

In [26]:
print(np.round(pos, 3))

[[ 0.     0.     0.   ]
 [ 0.     0.    10.   ]
 [ 0.     7.071 17.071]
 [ 0.     7.071 17.071]
 [ 0.     7.071 22.071]]


###### Матрица вращения по координатам звеньев из обратной задачи

In [27]:
print(np.round(pos_ik, 3))

[[ 0.     0.     0.   ]
 [ 0.     0.    10.   ]
 [ 0.     7.071 17.071]
 [ 0.     7.071 17.071]
 [ 0.     7.071 22.071]]


###### Матрица вращения по изначальным координатам звеньев

In [28]:
print(np.round(R, 2))

[[-1. -0. -0.]
 [ 0. -1.  0.]
 [-0.  0.  1.]]


###### Матрица вращения по координатам звеньев из обратной задачи

In [29]:
print(np.round(R_ik, 2))

[[-1. -0. -0.]
 [ 0. -1.  0.]
 [-0.  0.  1.]]
