## Позиции звеньев манипулятора и результирующая матрица поворота

![screenshot](../static/lab4.jpg)

#### Импорты

In [6]:
import math

import numpy as np
import sympy as sy

from lab4.function4lab import positionsAndRotate

#### Координаты звеньев (theta1, d2, theta3)

In [7]:
joint_coords = [math.pi, -10, math.pi / 2]

#### Параметры Денавита-Хартенберга манипулятора

In [8]:
theta1, theta3, d2 = sy.symbols('theta1'), sy.symbols('theta3'), sy.symbols('d2')

d = [10, d2, 0, 5]
r = [0, 0, 0, 0]
thetas = [theta1, -math.pi / 2, -math.pi / 2 - math.pi / 4 + theta3, -math.pi / 2]
alpha = [-math.pi / 2 - math.pi / 4, -math.pi / 2, -math.pi / 2, 0]

arg = {theta1: joint_coords[0], d2: joint_coords[1], theta3: joint_coords[2]}

#### Вычислении позиций и матрицы поворота

In [9]:
pos, R = positionsAndRotate(d, r, thetas, alpha, arg)

##### Позиции

In [10]:
print(np.round(pos, 3))

[[ 0.     0.     0.   ]
 [ 0.     0.    10.   ]
 [ 0.     7.071 17.071]
 [ 0.     7.071 17.071]
 [ 0.     7.071 22.071]]


##### Матрица поворота

In [11]:
print(np.round(R, 2))

[[-1. -0. -0.]
 [ 0. -1.  0.]
 [-0.  0.  1.]]
