## Создание матрицы Денавита-Хартенберга


#### Импорты

In [3]:
import math

import numpy as np
import sympy as sy

from src.support_function import templateDevidChart
from src.support_function import toNumpy

#### Символьный вид

In [4]:
sy.init_printing(use_unicode=True)
r, a, d, theta = sy.symbols('r'), sy.symbols('a'), sy.symbols('d'), sy.symbols('theta')
m = templateDevidChart(r, a, d, theta)
sy.pprint(m)

⎡cos(θ)  -sin(θ)⋅cos(a)  sin(a)⋅sin(θ)   r⋅cos(θ)⎤
⎢                                                ⎥
⎢sin(θ)  cos(a)⋅cos(θ)   -sin(a)⋅cos(θ)  r⋅sin(θ)⎥
⎢                                                ⎥
⎢  0         sin(a)          cos(a)         d    ⎥
⎢                                                ⎥
⎣  0           0               0            1    ⎦


#### Численный вид

In [5]:
m = m.evalf(subs={r: 5, a: 0, d: 3, theta: math.pi / 2})
print(np.round(toNumpy(m), 2))

[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  5.]
 [ 0.  0.  1.  3.]
 [ 0.  0.  0.  1.]]
